#!/bin/bash

#
# This script will set up an environment for modifying the disk image.
#

if [ ! -d disk ]; then
    echo "STOP: Disk directory does not exist.  Run ./deploy first."
    exit 1
fi

if [ $UID -ne 0 ]; then
    echo "STOP: This script must be run as root."
    exit 1
fi

# Enter the disk directory.
pushd disk >/dev/null

# Ensure qemu-linux-user is installed.
echo "edisk: Ensuring QEMU ARM layer is installed and enabled..."
zypper install qemu-linux-user
qemu-binfmt-conf.sh >/dev/null 2>/dev/null

# Perform bind mounts.
echo "edisk: Performing bind mounts..."
mount --bind /proc proc
mount --bind /sys sys
mount --bind /dev dev
mount --bind /dev/pts dev/pts

# Copy DNS resolution config.
echo "edisk: Copy DNS resolution config..."
cp /etc/resolv.conf etc/

# Enter chroot.
echo "edisk: Entering chroot.  Enjoy!"
chroot . $*

# Disable bind mounts.
echo "edisk: Stopping bind mounts..."
umount -lf dev/pts
umount -lf dev
umount -lf sys
umount -lf proc

# Leave the disk directory.
popd >/dev/null

exit 0
